apiVersion: v1
kind: Service
metadata:
  name: test-workflow3
  namespace: sample-app-namespace-1739995595001
  labels:
    app.kubernetes.io/name: test-workflow3
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test-workflow3
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000