apiVersion: v1
kind: ConfigMap
metadata:
  name: test-workflow-config
  namespace: sample-app-namespace-1739987625754
  labels:
    app.kubernetes.io/name: test-workflow
    kubernetes.azure.com/generator: devhub
data: