apiVersion: v1
kind: Service
metadata:
  name: test-workflow2
  namespace: sample-app-namespace-1739988650776
  labels:
    app.kubernetes.io/name: test-workflow2
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test-workflow2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080