apiVersion: v1
kind: Service
metadata:
  name: test-workflow1
  namespace: sample-app-namespace-1739991770521
  labels:
    app.kubernetes.io/name: test-workflow1
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: test-workflow1
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002